FIND_PACKAGE(MPI)

IF(MPI_FOUND)
  
  INCLUDE_DIRECTORIES(${MPI_INCLUDE_PATH})

	#compatibility layer with MS MPI
  IF(YOCTO_WINDOWS AND YOCTO_GNU)
    ADD_DEFINITIONS( -DMSMPI_NO_SAL=1 )
  ENDIF()

ENDIF()
